### ISSUE TITLE
java.lang.IllegalStateException: Could not find matching project info read

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate-cli#25]
## Issue

dekorate generates the following error if it is executed within an empty folder

```
~/code/dekorate/testing  dekorate kubernetes
java.lang.IllegalStateException: Could not find matching project info read
	at io.dekorate.project.FileProjectFactory.lambda$createInternal$0(FileProjectFactory.java:62)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.dekorate.project.FileProjectFactory.createInternal(FileProjectFactory.java:62)
	at io.dekorate.project.FileProjectFactory.create(FileProjectFactory.java:43)
	at io.dekorate.cli.Generator.init(Generator.java:38)
	at io.dekorate.cli.KubernetesCmd.run(KubernetesCmd.java:23)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1839)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2326)
	at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2328)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2323)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2286)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at io.dekorate.cli.Main.run(Main.java:19)
	at io.dekorate.cli.Main_ClientProxy.run(Main_ClientProxy.zig:157)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

Question: What are the prerequisites to be documented which are needed in order to execute properly the CLI ?

**Comment by iocanel** [comment]
Dekorate requires a known project type.

Currently supporting:

- maven
- gradle
- sbt
- bazel
- npm

Let me see if we can improve the error message.
